flyerhzm/bullet

lib/bullet/active_record41.rb
lib/bullet/active_record42.rb

in AR 4.1 and 4.2, to_sql calls find_with_associations
to attach relevant joins so that the produced SQL matches
the sql actually used when running the query. Bullet's
monkey-patch of find_with_associations calls the original
without a block so it actually passes the query to
the DB connection and runs it.
This commit simply branches the monkey-patch on
block_given? to make it consistent with AR's
definition of the same method. To wit, when
find_with_associations is called by a block, it
yields a new relation with the correct associations
joined and doesn't pass the query on to the DB.

don't execute query when running to_sql

---

lib/bullet/notification/n_plus_one_query.rb

I think we can send backtrace of N+1 problem to uniform_notifier.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/flyerhzm/bullet/218)

Send backtrace to uniform_notifier

---

lib/bullet.rb

a484c0c329 dynamically mapped the available notifiers, breaking 1.8.7
compatibility:
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `require':
/home/vagrant/gems/ruby/1.8/gems/bullet-4.14.5/lib/bullet.rb:32: syntax
error, unexpected tSYMBEG, expecting tAMPER (SyntaxError)
...|notifier| "#{notifier}=" }, :to => UniformNotifier
^
/home/vagrant/gems/ruby/1.8/gems/bullet-4.14.5/lib/bullet.rb:165: syntax
error, unexpected kDO_BLOCK, expecting kEND
notification_collector.collection.each do |notification|
^
/home/vagrant/gems/ruby/1.8/gems/bullet-4.14.5/lib/bullet.rb:172: syntax
error, unexpected kDO_BLOCK, expecting kEND
...ector.collection.inject({}) do |warnings, notification|
^
/home/vagrant/gems/ruby/1.8/gems/bullet-4.14.5/lib/bullet.rb:172: syntax
error, unexpected '|', expecting '=' …

1.8 compatible deletgated available notifiers

---

lib/bullet/active_record3x.rb

Using Ruby >=  2.2.x, whenever Bullet would check if a model has a cache_counter, it would error out with `undefined method 'name' for nil:NilClass`. 
It seems to be an issue with the way that Ruby 2.2 warns about circular argument references
```
=> Booting WEBrick
=> Rails 3.2.21 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
/bullet/lib/bullet/active_record3x.rb:146: warning: circular argument reference - reflection
[2015-06-04 12:40:19] INFO  WEBrick 1.3.1
[2015-06-04 12:40:19] INFO  ruby 2.2.2 (2015-04-13) [x86_64-darwin14]
[2015-06-04 12:40:19] INFO  WEBrick::HTTPServer#start: pid=7964 port=3000
```

Fixes circular argument reference error for AR 3x for Ruby > 2.2.x

---

lib/bullet/active_record4.rb
lib/bullet/active_record41.rb
lib/bullet/active_record42.rb
spec/integration/active_record4/association_spec.rb

Do not report association queries immediately after object creation to require a preload

---

Gemfile.mongoid-5.0

mongoid 5 is currently in prerelease, so this specifier is needed to use that version from the repository. Introduced by mongoid/mongoid@507d7a794f6edd5f2b1a2b86c922340f3cf7d9c2.

Rename to mongoid 5.0.0-beta.

---

lib/bullet.rb
spec/bullet_spec.rb
spec/spec_helper.rb

Fixes #247.
I'm not sure if this is the best way to do it -- it seems every detector checks start?

start? should check enabled?

---

lib/bullet.rb
lib/bullet/active_record3.rb
spec/bullet_spec.rb

I was using `rack-mini-profiler` on my application and noticed that `bullet` was creating a large number of strings to be garbage collected. This is a simple change that will greatly reduce the number of strings that need to be garbage collected.
Before the change
151209 : load_target
4355 : BULLET_DEBUG
4874 : true
After the change
519 : true
For this request, more than 160000 strings were saved from being created.

Reduce object count

---

README.md
lib/bullet.rb
lib/bullet/detector/n_plus_one_query.rb
spec/bullet/detector/n_plus_one_query_spec.rb

Hi,
We had a need to exclude n+1 detection based on the caller stack trace, as some of the n+1 detection occuring was not whitelistable using the standard whitelist object/association feature.  I added an option called `stacktrace_excludes` to mirror the `stacktrace_includes` option that already exists.
Please let me know your thoughts.
Thanks for the great tool!

Add stacktrace_excludes option

---

lib/bullet/detector/unused_eager_loading.rb
spec/bullet/detector/unused_eager_loading_spec.rb

example:
```ruby
Post.includes(:comments).each { |p| p.comments }  # [post1, post2]
Post.includes(:comments, :tags).each { |p| p.comments; p.tags } # [post1, post3]
```
both two query results include same object _post1_, incorrectly show the warning.

[UnusedEagerLoading] multiple eager loading query include same objects 

---

lib/bullet.rb
spec/bullet_spec.rb

1. Create a class named Loss, which belongs to a User
2. Add a N+1 query that reads losses.user
3. Whitelist the association
Expected: The query is not flagged
Actual: The query is flagged 
```
N+1 Query detected
Loss => [:user]
Add to your finder: :includes => [:user]
```
N+1 query whitelists are not respected for classes like Loss, Status because calling `classify` alters the key names to Los, Statu
Do not call classify on the klass names.

Fix whitelisting bug for classes ending w/ S

---

Hacking.md

Leaving no blank lines above the ordered list will make it a single-line mess. Simply adding a blank line fixes this.

Fix the ordered list

---

.travis.yml

The Ruby 1.9.3 build consistently fails for Rails 4.x versions.
This is due to a dependency on the [`mime-types-data` gem which is not compatible with Ruby < 2.x](https://rubygems.org/gems/mime-types-data).
These are two failing Travis  builds for reference:
- https://travis-ci.org/flyerhzm/bullet/builds/118186461
- https://travis-ci.org/flyerhzm/bullet/builds/127187543
Therefore, exclude the following configurations:
- Ruby 1.9.3 and Rails 4.0
- Ruby 1.9.3 and Rails 4.1
- Ruby 1.9.3 and Rails 4.2

Disable Travis builds for failing configurations

---

lib/bullet/rack.rb
spec/bullet/rack_spec.rb

When using a setup like e.g. Grape mounted on Rack, the response body will still be nested under `response.body`. Yet, the Gem will try to access `.first` on the response object, which leads to method not found exception.
Instead of checking if the Gem is running in a Rails environment (via `rails?`) we can check if a response has a `body` set, and if so, return this. If not, the fallback will remain to be the `response.first` call.

Add response handling for non-Rails Rack responses

---

lib/bullet.rb

Given the Luke class
```lang=ruby
class Luke
def father
Bullet.profile do
:darth_fader
end
end
end
```
`Bullet.profile` now returns the return value of the block given. In this example the `father` will behave like:
```lang=ruby
> Luke.new.father
=> :darth_fader
````
It also returns the value regardless the enabled or disabled state of Bullet
```lang=ruby
> Bullet.enable = true
=> true
> Luke.new.father
=> :darth_fader
> Bullet.enable = false
> Luke.new.father
=> :darth_fader
````

[WIP] .profile respects the return value of the given block

---

lib/bullet.rb
lib/bullet/rack.rb
spec/bullet/rack_spec.rb
spec/bullet_spec.rb

Bullet `notification.url` will sometimes be empty. Because a notification url is a env['REQUEST_URI'] and it does not necessarily exist.
In general, REQUEST_URI is provided by a Web server like WEBrick, Unicorn, puma, ...
But in the test code,
RSpec's Request spec:
* Rails integration test set a REQUEST_URI
* ref: https://github.com/rails/rails/blob/173bf3506d99c0767a41d30fbe4d306201369194/actionpack/lib/action_dispatch/testing/integration.rb#L354
RSpec's Feature spec:
* RackTest, Capybara's default driver interacts directory with Rack interface
* [Rack envirionment](http://www.rubydoc.info/github/rack/rack/file/SPEC) does not include REQUEST_URI
In this PR, build dummy REQUEST_URI using PATH_INFO and QUERY_STRING when it is empty.

Build request uri when env['REQUEST_URI'] does not exist

---

lib/bullet.rb
lib/bullet/detector/n_plus_one_query.rb
lib/bullet/detector/unused_eager_loading.rb
lib/bullet/notification/unused_eager_loading.rb
lib/bullet/stack_trace_filter.rb
spec/bullet/detector/n_plus_one_query_spec.rb
spec/bullet/detector/unused_eager_loading_spec.rb
spec/bullet/notification/unused_eager_loading_spec.rb

- Extracts stack trace filtering into module.
- Adds stack trace filtering to unused eager loading detector.
- Adds ability to filter by either caller path includes substring or caller path matches regex.

Stacktrace filter module

---

README.md
lib/bullet/rack.rb

I always end up opening developer tools and removing the footer so I can click on some button. So I added a close button to the top right of the footer to make life easier. I didn't realize that double clicking the footer would also close this until I was editing the code for this.

Add close button to footer

---

.gitignore
lib/bullet/notification/n_plus_one_query.rb
lib/bullet/notification/unused_eager_loading.rb
spec/bullet/notification/n_plus_one_query_spec.rb
spec/bullet/notification/unused_eager_loading_spec.rb

I was getting double backtraces when N+1 Queries were detected. This fixes that.
Additionally, I changed `N+1 Query` to `USE eager loading` and `Unused Eager Loading` to `AVOID eager loading` for symmetry and for making the suggestion more relevant.

Avoid double backtrace

---

lib/bullet/active_record5.rb

Hi!
I'm not sure if this related to rails < 5.0.1, I haven't check their source. But this change will not break anything.
Here https://github.com/rails/rails/blob/5-0-stable/activerecord/lib/active_record/relation.rb#L702 `find_by_sql` is called with block from https://github.com/rails/rails/blob/5-0-stable/activerecord/lib/active_record/association_relation.rb#L33 which sets inverse values. As in patched versions block is not passed, inverse values are not set. This results in false warnings for code like this one `order.items.map(&:order)` (with `inverse_of`).
I'm not familiar with bullet's test, so haven't added one for this.
WDYT about change args in all methods to `*args, &block` and to call original methods with this args. It would without change if they would add new kwargs or …

Fix inverse_of for rails 5

---

README.md

I also removed the word 'seven' since there are more than seven notification systems now.
I noticed that `raise` isn't mention in the configuration code, not sure if this is intentional or not.

Re-order notifier explanations to match configuration example

---

Gemfile

This PR suppresses the following warnings.
```sh
% bundle install
The git source `git://github.com/rails/rails.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
```
Refer: https://github.com/bundler/bundler/pull/4127

Use secure protocol when running `bundle install`

---

Gemfile.rails-5.0
Gemfile.rails-5.1

Here's a trivial patch that lets the CI run on newer stable versions of Rails 5.0.x and 5.1.x.

Testing with newer Rails 5 gems

---

lib/bullet/stack_trace_filter.rb
spec/bullet/detector/n_plus_one_query_spec.rb

Since the filter is only interested in the path, it can be extracted
from the Location object, rather than a string representing it.
This reduces the memory usage of that file to 1/3.
(3MB to 1MB per request in a large app)

Don't serialise caller locations

---

lib/bullet/detector/association.rb
lib/bullet/detector/n_plus_one_query.rb
lib/bullet/ext/object.rb
lib/bullet/ext/string.rb
lib/bullet/notification/base.rb

A few strings are frozen to make fewer allocations. In a fairly big app, this saved 5k+ trivial allocations per request.

Freeze strings

---

lib/bullet/active_record5.rb

When you `preload` a `has_one :through` association, Rails loads the intermediate association followed by the source association.
Rails 5 [changed how the intermediate results are accessed](https://github.com/rails/rails/commit/842f5c2dad8ed021274c16f2dc231c15ddefba18) during preloading such that `#reader` is bypassed. As a result, Bullet is unaware that these associations have been accessed (i.e. `Bullet::Detector::NPlusOneQuery.call_association` isn't called).
This results in false positive avoid eager loading warnings from the model to the intermediate association as well as from the intermediate association to the source association.
More details in #323 
This PR addresses the issue by overriding `target` instead of `reader`, so that the access to intermediate associations is tracked …

Fix Rails 5 false positive for intermediate (through) associations

---

lib/bullet/stack_trace_filter.rb

We updated bullet to 5.6.0 at own project, but we have received below exception.
```
NoMethodError: undefined method `include?' for nil:NilClass
from /Users/yukihattori/.anyenv/envs/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bullet-5.6.0/lib/bullet/stack_trace_filter.rb:10:in `block in caller_in_project'
```
According to the source code of Ruby,  [`Thread::Backtrace::Location#absolute_path` seems to be able to return `nil`](https://github.com/brightbox/deb-ruby2.3/blob/master/vm_backtrace.c#L241). It would become raising `NoMethodError` at `include?`. I could not find the procedure for reproducing clearly because I'm not familiar with Ruby core.
We would be able to deal with it by using `to_s` to convert from `nil` to empty string.

Fix caller path in the case of nil

---

lib/bullet.rb
spec/bullet_spec.rb

Hi there,
I use Bullet gem with RSpec gem.
Rarely I want to enable a whitelist definition temporary in my spec.
For example, for feature toggle which completely separate the logic.
And then, Bullet warns me "N+1 DETECTED" at feature A spec. On the other side, Bullet warns me "AVOID UNUSED EAGER LOADING" at feature B spec.
So, I add the whitelist definition temporary in my spec, and after the spec running, I want to delete the whitelist definition not clear all definitions.
```ruby
describe 'User#some_method' do
subject { user.some_method }
context 'when feature A is enabled' do
before { Bullet.add_whitelist type: :n_plus_one_query, class_name: 'User', association: :profile }
after    { Bullet.delete_whitelist type: :n_plus_one_query, class_name: 'User', association: :profile }
...
end …
```

Implement Bullet.delete_whitelist to delete a specific whitelist definition

---

lib/bullet/active_record52.rb
lib/bullet/dependency.rb

In ActiveRecord 5.2 (aka current edge Rails) there was a small change to the `instantiate` method on join dependencies (see rails/rails@1a723c6).
I've no idea how to test this properly, so tests should be added to this PR.

Add support for ActiveRecord 5.2

---

lib/bullet.rb

This PR suppresses the following warning.
```
ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
RUBYOPT=-w bundle exec rake 
/Users/numata/git/github.com/flyerhzm/bullet/lib/bullet.rb:38: warning: `*' interpreted as argument prefix
/Users/numata/git/github.com/flyerhzm/bullet/lib/bullet.rb:48: warning: method redefined; discarding old enable=
/Users/numata/git/github.com/flyerhzm/bullet/lib/bullet.rb:158: warning: method redefined; discarding old notification_collector
```

Suppress warnings

---

CHANGELOG.md
README.md
bullet.gemspec
lib/bullet/version.rb

Following your comment [here](https://github.com/flyerhzm/uniform_notifier/issues/37), I tried to update the `uniform_notifier` without bumping the version of `Bullet`, but I can't make it works.
Maybe it's because `uniform_notifier` is specified in `bullet.gemspec`?

Update uniform_notifier dependency

---

lib/bullet/stack_trace_filter.rb

Seems like bullet only excludes a hardcoded /vendor path, while my setup puts things under /.bundle. The Bullet.stacktrace_excludes doesn't clean out all those lines as I thought it would, so adding it this way cleans up my logs tremendously. Hopefully this PR will be helpful for others!

Exclude configured bundler path in addition to '/vendor'

---

bullet.gemspec

This reduces an unneeded redirection from http://... to https://... when someone visits this gem's homepage via https://rubygems.org/gems/bullet

GitHub is HTTPS by default

---

lib/bullet/dependency.rb

When trying to use an unsupported ActiveRecord version, currently the gem blurts out this:
`Gem Load Error is: Bullet does not support active_record ActiveRecord::VERSION yet`
We should use `ActiveRecord::VERSION::STRING` in the interpolation. [`::STRING`](https://github.com/rails/rails/blob/1c383df324fdf0b68b3f54a649eb7d2a4f55bcb7/activerecord/lib/active_record/gem_version.rb#L15 ) resolves to a proper version (like `5.2.0`), so the error message would be something like: 
`Gem Load Error is: Bullet does not support active_record 5.2.0 yet`

Fixes error message when using unsupported AR.

---

README.md
lib/bullet/stack_trace_filter.rb
spec/bullet/detector/n_plus_one_query_spec.rb

it's not uncommon to have code that preloads (or not) for the common case,
but for certain data layouts it will generate a Bullet warning. it should
be possible to exclude just that small piece of code, rather than all
violations in the entire file

extend stacktrace matching for sub-file precision

---

README.md

As it currently stands, the skip_bullet function in the readme will always result in bullet being enabled, even if it was originally disabled.

Update skip_bullet in readme to use previous value

---

lib/bullet/mongoid6x.rb

I've got the following `ArgumentError` on mongoid v6.4.1 and bullet v5.7.6.
```
ArgumentError: wrong number of arguments (given 1, expected 0)
from /sample/example/bullet-5.7.6/lib/bullet/mongoid6x.rb:13:in `first
```
Because mongoid6.x changed to support a option argument for `Mongoid::Contextual::Mongo#first` and `#last`. https://github.com/mongodb/mongoid/commit/346316d7f139300ab0dfafe5a6cf105176942e8f#diff-9f2758fc31a36227f2e9932b142db328R237
So I added the argument to bullet.

Support a option for `Mongoid::Contextual::Mongo#first` and `#last` on mongoid6.x

---

lib/bullet/active_record5.rb
lib/bullet/active_record52.rb
spec/integration/active_record/association_spec.rb
spec/models/client.rb
spec/models/firm.rb
spec/models/group.rb
spec/support/sqlite_seed.rb

I found a wrong detection when set nested "through" to "includes" at ActiveRecord 5.2.
Because "#through_reflection" was changed.
(AR5.1)
https://github.com/rails/rails/blob/5-1-stable/activerecord/lib/active_record/associations/through_association.rb#L5
(AR5.2)
https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/associations/through_association.rb#L10-L20

Fix multiple through bug

---

bullet.gemspec

This https://github.com/flyerhzm/bullet/commit/3ab8e3a2ac67d9dcbcdcb0dbe4510252b09af739 commit broke the gem for Ruby 2.2 and below, as the safe navigation operator was added only in Ruby 2.3.
I'm aware Ruby 2.2 is EOL but it may brake people's projects (it broke one of mine).

Require Ruby 2.3+ in  in gemspec

---

lib/bullet/mongoid7x.rb

Auto corrected by following Ruby EmptyLine
Click [here](https://awesomecode.io/repos/flyerhzm/bullet/ruby_config_groups/49) to configure it on awesomecode.io

Auto corrected by following Ruby EmptyLine

---

lib/bullet/detector/association.rb
lib/bullet/detector/counter_cache.rb
lib/bullet/detector/n_plus_one_query.rb
lib/bullet/detector/unused_eager_loading.rb
lib/bullet/ext/object.rb
spec/bullet/ext/object_spec.rb

Two changes here:
1. I renamed `Object#primary_key_value` to `Object#bullet_primary_key_value` to make it clear that this core extension is specific to `bullet` and to avoid potential naming conflicts. (This feels at least to me like a semi-private method that shouldn't be used by external code...)
2. I added a test case and made code modifications to handle the case when a primary key value has been manually set on an unpersisted record. One might commonly do this, for instance, in a test context (to avoid making unnecessary database round-trips).
Here's a very contrived example:
```ruby
post = user.posts.build(id: 123)
comment = post.comments.build(text: 'hey, cool post')
email = WeeklySummaryEmail.new(user: user)
expect(email.subject).to eq "1 new comment on post 123!"
```
Previously, …

Handle unpersisted primary key values

---

lib/bullet.rb
lib/bullet/dependency.rb
lib/bullet/stack_trace_filter.rb

In one of our non-Rails projects we added ActionMailer. It comes along
with a number of dependencies and modules namespaced under `Rails`.
The problem is that we don't have a Rails app and therefore `Rails.root`
is not defined. This causes bullet to blow up when getting `Rails.root`. 
The fix is to be more specific with the check. I also consolidated the
logic to one method since `rails?` was only ever used to check if Bullet
should call `Rails.root`. A similar approach is taken in many other libraries and seems to work well: https://github.com/search?q=defined%3F%28Rails.root&type=Code

Make Rails check more specific

---

lib/bullet/active_record4.rb
lib/bullet/active_record41.rb
lib/bullet/active_record42.rb
lib/bullet/active_record5.rb
lib/bullet/active_record52.rb
spec/integration/active_record/association_spec.rb

Spec in 582b2d4b actually not passes, which I fixed at 314a43d (CI red).
After reverting the commit, other specs are still good.

Add missing `check_unused_preload_associations` call to spec

---

CHANGELOG.md

I'm not sure this is correct, but according to rubygems, it seems 6.0 released in April. 
https://rubygems.org/gems/bullet/versions/6.0.0 
If you intend to do this in February, please close this. Thanks!

Fix release date of 6.0.0

---

lib/bullet/bullet_xhr.js

I found the error on IE11, but Chrome ignores it 🤔.

fix syntax error

---

lib/bullet/bullet_xhr.js

When used with Turbolinks, users are presented with _maximum call stack exceeded_ errors which prevents the pages from rendering.
1. Using any version of Turbolinks.
1. Navigate to a page that returns a Bullet error.
1. Navigate to another page with a Bullet error.
1. Navigate anywhere else.
Because Turbolinks doesn't reload the page `XMLHttpRequest.prototype.open` and `send` are not reset on page load. When we extend these functions, we keep track of the original implementation and call it at the end. If we do this twice in a row, we recursively call the same function which results in the described error.
Check for function names of `open` and `send`. If they've been changed to Bullet functions, return.
More descriptive function names and removal of unused arguments.
Closes #454

Prevent "Maximum call stack exceeded" errors when used with Turbolinks

---

README.md

What the title says. If it happens that someone adds that code carelessly they'll get their production server down without noticing it in dev or test envs.
https://github.com/flyerhzm/bullet/issues/106

Fix README to prevent issues on production

---

lib/bullet/notification/base.rb
lib/bullet/notification/n_plus_one_query.rb
lib/bullet/notification/unused_eager_loading.rb
spec/bullet/notification/n_plus_one_query_spec.rb
spec/bullet/notification/unused_eager_loading_spec.rb

Current warning uses old `:include => []` syntax which does not work in Rails, not 100% on Mongoid but I do know it supports `.includes()`.

Use modern includes syntax in warnings

---

lib/bullet.rb

I have just install ruby-2.7.0-preview3 and see the warning in the console
`warning: The last argument is used as the keyword parameter`
.rbenv/versions/2.7.0-preview3/lib/ruby/gems/2.7.0/gems/bullet-6.0.2/lib/bullet.rb:42: warning: The last argument is used as the keyword parameter
this PR fixes warning

warning: The last argument is used as the keyword parameter

---

CHANGELOG.md
README.md
lib/bullet.rb
lib/bullet/rack.rb
spec/bullet/rack_spec.rb

The reason that I am opening this PR is because we would
like to have bullet running in certain environments to log
to the standard Rails logger without having it enabled at
all in the UI. We also have a strict CSP and do not wish
to open it up for Bullet since we do not need these features.

Add `skip_html_injection` flag

---

lib/bullet.rb
lib/bullet/rack.rb
spec/bullet/rack_spec.rb

We've got a similar usecase as https://github.com/flyerhzm/bullet/pull/484 where we're just using the logging notifiers.
Debugging the issue I ran into the newly added `skip_html_injection` flag, however I think we can go further than that, bullet has enough information to know whether we want the HTML injections or not, so this PR adds logic to only add the HTML/XHR info if one of the notifiers that relies on it is enabled.
This probably negates the usecase of that flag, but I haven't removed it in this PR.

Don't modify response body if not using relevant notifiers

---

lib/generators/bullet/install_generator.rb

I am not good at English, so please understand that the sentence may be strange...
Also, since this is the first time that you have posted a PR to a human repository, please point out if the procedure is wrong.
```
bundle exec rails g bullet:install
```
When the enable `bullet` using the above command, the settings will be added to environment files like:
```ruby
Rails.application.configure do
config.after_initialize do
Bullet.enable        = true
Bullet.alert         = true
Bullet.bullet_logger = true
Bullet.console       = true
Bullet.rails_logger  = true
Bullet.add_footer    = true
end  # Settings specified here will take precedence over those in config/application.rb.
```
```ruby
Rails.application.configure do
config.after_initialize do
Bullet.enable        = true
Bullet.bullet_logger …
```

Fixed spaces around settings

---

lib/bullet/rack.rb

:wave: Hey, there. Big fan of this gem, it's super helpful.
This PR updates the design of the footer notification for displaying bullet warnings to be less intrusive, but still noticeable.
Old design:
New design:
The footer now uses native `<detail>` and `<summary>` tags so it can be opened and closed by clicking the "Bullet Warnings" heading.
I've modeled the design after the footer badge from `rack-mini-profiler`, which I really like.

Update design for footer notification

---

lib/bullet/rack.rb
spec/bullet/rack_spec.rb

In Rails 6, the spec of `ActiveSupport::SafeBuffer#insert` has been changed.
Previously, it behaves like just String, but now `ActiveSupport::SafeBuffer` exactly.
See for details: https://github.com/rails/rails/pull/33990
This change breaks bullet notification in HTML.
In Rails 5.2.
``` ruby
"".html_safe.insert 0, '<a>hi</a>' #=> '<a>hi</a>'
```
In Rails 6.
``` ruby
"".html_safe.insert 0, '<a>hi</a>'  #=> "&lt;a&gt;hi&lt;/a&gt;"
```
Close https://github.com/flyerhzm/bullet/issues/488, https://github.com/flyerhzm/bullet/issues/513

Fix to render bullet notification as html safe string

---

lib/bullet/bullet_xhr.js

These add no benefit to the code and make it incompatible with IE <= 11.
Using simple functions work just as well and make it work in a broader set of browsers.

Removing arrow functions from bullet_xhr.js

---

lib/bullet/mongoid4x.rb
lib/bullet/mongoid5x.rb
lib/bullet/mongoid6x.rb
lib/bullet/mongoid7x.rb

Auto corrected by following Lint Ruby Performance/BlockGivenWithExplicitBlock
Click [here](https://awesomecode.io/repos/flyerhzm/bullet/lint_configs/ruby/101417) to configure it on awesomecode.io

Auto corrected by following Lint Ruby Performance/BlockGivenWithExplicitBlock

---

lib/bullet.rb
lib/bullet/stack_trace_filter.rb

`Gem::Version.new` and `Gem::Version#<=>` took more than half of all the execution time of `Bullet::Detector::NPlusOneQuery.call_association`, and `Bullet.app_root` roughly 1/5 more. None of this is changed without the app restart, so it's safe to calculate them once.
Before:
After:
Backstory: I was profiling an app with N+1s in it and realized that Bullet eats a lot of time, and `Gem::Version` takes most of it. After this patch `call_association` method time changed from 1300ms to 400ms. 
Last but not least, you are doing great job with this gem, I can't count how many times it helped me. Thank you!

Calculate Bullet.app_root and IS_RUBY_19(former ruby_19?) once

---

README.md

The readme says that `skip_html_injection` prevents "XHR" from being injected into the page. That's not really what this option does - it prevents HTML from being injected (and also adds javascript to the page to intercept XHR requests).
I've tweaked the wording so it's clearer that this isn't just about XHR.

Make readme clearer about what `skip_html_injection`

---

CHANGELOG.md
README.md
lib/bullet.rb
lib/bullet/rack.rb
spec/bullet/rack_spec.rb

Right now if the console or footer options are enabled, then API requests will include extra headers for bullet. These only exist to power the XHR script that's included in HTML pages, which are irrelevant to an API request. At the moment there's no way to disable this, so I've added a new option for it. Because disabling these headers prevents the XHR javascript hooks from working, I've also made the new option prevent the XHR javascript from being added to pages.
As part of this I cleaned up a handful of related tests that test existing behaviour, so I've put those changes in a separate commit.

Added a "skip http headers" option

---

lib/bullet.rb

Auto corrected by following Lint Ruby Lint/DeprecatedConstants
Click [here](https://awesomecode.io/repos/flyerhzm/bullet/lint_configs/ruby/106330) to configure it on awesomecode.io

Auto corrected by following Lint Ruby Lint/DeprecatedConstants

---

lib/bullet.rb

Fixes #568 by checking if Rails.root is both _defined and different than nil_ before using it.

Do not use `Rails.root` if it's nil

---

spec/bullet/ext/object_spec.rb
spec/integration/active_record/association_spec.rb
spec/integration/mongoid/association_spec.rb

Fix typo in following files
- spec/integration/mongoid/association_spec.rb
- spec/integration/active_record/association_spec.rb
- spec/bullet/ext/object_spec.rb

Fix typo in tests

---

lib/bullet/bullet_xhr.js

XMLHttpRequest overrided by bullet_xhr.js is call twice `onload` callback.
1. `this.onload`
2. `_storedOnload` copied from `this.onload`
So I fixed it to disable case 1.

Fix onload called twice

---

lib/bullet/rack.rb
spec/bullet/rack_spec.rb

When using the `Rack::Static` middleware, the response will be a `Rack::Files::Iterator`. Such a response will break
`Bullet::Rack#response_body`, with the result that non-HTML files will not be served correctly.
Seen when trying to use the Sidekiq admin engine in a Rails application that also uses Bullet.

Support Rack::Files::Iterator responses

---

lib/bullet/detector/n_plus_one_query.rb
lib/bullet/stack_trace_filter.rb
spec/integration/active_record/association_spec.rb
spec/models/deal.rb
spec/models/post.rb
spec/support/sqlite_seed.rb
test.sh

Fixes #546 
Prior to this commit, unless your HABTM join table excluded the `id`
primary key column, it would be erroneously marked as a potential n+1
query. Other HABTM queries that had join tables _without_ an `id` column
were properly ignored. This exclusion _seems_ to be a side-effect of
excluding objects that don't have primary keys/id columns in an effort
to ignore non-persisted objects (stemming from [this commit](https://github.com/flyerhzm/bullet/blob/2c8a6d26f4a11bc8b3af5ff7da815401049732d4/lib/bullet/detector/n_plus_one_query.rb#L37)).
This commit, instead, explicitly ignores HABTM models when checking for potential
objects that could have a n+1 impact since they are join tables that
typically aren't queried for specifically but instead are joined on.

Bug: Ensure HABTM associations are not incorrectly labeled n+1

---

README.md
lib/bullet.rb
lib/bullet/detector/counter_cache.rb
lib/bullet/detector/n_plus_one_query.rb
lib/bullet/detector/unused_eager_loading.rb
spec/bullet_spec.rb
spec/integration/active_record/association_spec.rb
spec/integration/counter_cache_spec.rb

Renames instances of `whitelist` to `safelist` and adds deprecation messages for the previous methods.
See https://github.com/flyerhzm/bullet/issues/510

Rename whitelist to safelist

---

lib/bullet/mongoid7x.rb

MongoDB/Mongoid uses cursors for queries by default, unlike SQL
dbs/ActiveRecord. Users of MongoDB expect that find operations by
default will behave like ActiveRecord's find_in_batches. It should be
possible to iterate over the results of a query and only the single
batch of results from the db should be in memory at one time, which
allows code to iterate over very large collections or collections with
large documents safely.
Bullet's Mongoid integration breaks this by consuming the entire
enumerable into memory before yielding. The code is now changed to
iteratively yield results.
I've only fixed the Mongoid 7 version because I've been able to validate its behavior against my app using Mongoid 7 whereas I cannot get any of the current Mongoid test suites in Bullet to function correctly.

Fix Mongoid 7 view iteration

---

lib/bullet/rack.rb
spec/bullet/rack_spec.rb

Fix empty? method condition when a response does not respond to **body**
This fix is related to a [question](https://github.com/flexport/bullet/pull/1#discussion_r363533973) in this feature  #436 https://github.com/flyerhzm/bullet/pull/436/files#diff-aba60c0c33aae80c889d4808092bb153L34

Fix empty? when a response does not have body

---

.github/workflows/main.yml

[Rails 7.0.1 was released which supports Ruby 3.1](https://rubyonrails.org/2022/1/6/Rails-7-0-1-has-been-released)

Run ruby 3.1 on github actions

---

README.md

The log format was changed in 2016 via [this commit](https://github.com/flyerhzm/bullet/commit/f28e3de1f04851b3cd1604173fe631e367799264#diff-bb91f407254e96333f143c39073b8170b6f1cbe0f327ece601785f08dcab31ce) but the documentation was never updated.
This was very confusing to our team because no one noticed that "Use eager loading detected" and "Avoid eager loading detected" were two separate issues! We thought the N+1 detection was just broken.

Update documentation to reflect updated log format

---

lib/bullet.rb
lib/bullet/active_record5.rb
lib/bullet/active_record52.rb
lib/bullet/active_record60.rb
lib/bullet/active_record61.rb
lib/bullet/active_record70.rb
lib/bullet/detector/counter_cache.rb
lib/bullet/detector/n_plus_one_query.rb
lib/bullet/detector/unused_eager_loading.rb

We had an issue https://github.com/rubyforgood/human-essentials/issues/3024 where we defined a `to_a` method on an ActiveRecord class. This method is a conversion method, meant to convert something (which may not be an array) into an array (which may not directly correspond with the original object).
For example, calling `to_a` on a hash will get you an array of key/value pairs of the hash.
This caused crashes on our local with bullet running, since the `Array()` method falls back to calling `to_a` on the object. In our case the result of this was not a list of ActiveRecord objects as expected.
ActiveSupport's `Array.wrap()` method, on the other hand, only uses `to_ary` (which is only implemented in array-like objects) and correctly wraps any single objects in an array without calling …

Replace Array() with Array.wrap()

---

README.md

The Rails example in the `README.md` contains a few incorrect paths: "app/model" should be "app/models" in two locations.
This PR fixes that.
I was able to completely follow the instruction after this change. Thank you for the step-by-step instructions, by the way!

Fix Rails example path in Readme

---

lib/bullet/mongoid7x.rb

Mongoid 7.5 deprecates the :id_sort keyword argument for the Criteria#first and Criteria#last methods.
If you use bullet gem along with Mongoid 7.5 or newer version, calling first() or last() method will raise an error that is caused by the parameter's default value change.
`Model.where(condition).first  => KeyError`
This PR fix the problem and support new first/last change on Mongoid 7.5
Reference: https://www.mongodb.com/docs/mongoid/current/release-notes/mongoid-7.5/#deprecate-id-sort-option-and-support-limit-on-first-last

mongoid7x: fix #first/last on 7.5

---

lib/bullet/active_record5.rb
lib/bullet/active_record52.rb
lib/bullet/active_record60.rb
lib/bullet/active_record61.rb
lib/bullet/active_record70.rb
spec/integration/active_record/association_spec.rb

Happens when  `eager_load` is used. Eager load uses a single query (with a left join) to pull the records and it doesn't build/load any records for the join table. Seems that using `if association.loaded?` solves the problem.

Fix false positive n+1 for has many through associations

---

lib/bullet/active_record70.rb
spec/integration/active_record/association_spec.rb

I don't know enough about this gem and AR to explain in detail what's wrong. But let me try:
What I've been able to assess is in AR 7.0, inversed objects don't get added when a children records get loaded via a query (?) instead of an association call 🤔 
Don't know if it explains well enough but right now, this doesn't raise an n+1 error
```ruby
Post.first.comments.each { _1.post.name }
```
but this does:
```ruby
Post.first.comments.all.each { _1.post.name }
```

Fix n+1 false positives in AR7.0

---

lib/bullet.rb
lib/bullet/detector/association.rb
lib/bullet/detector/n_plus_one_query.rb
lib/bullet/detector/unused_eager_loading.rb
lib/bullet/registry.rb
lib/bullet/registry/call_stack.rb
lib/bullet/stack_trace_filter.rb
spec/bullet/detector/unused_eager_loading_spec.rb

Hello! I think this is working solution for problem:
https://github.com/flyerhzm/bullet/issues/384
Btw, this problem can occurs on Puma servers or RSpec testing (my current build Rails 5.2.X + Ruby 2.7.5) in case originally "broken" query backtrace always behind borders of :caller_locations method called in StackTraceFilter. So I thought memorizing original backtrace could be a good decision.

Added CallStacks support for avoid eager loading

---

lib/bullet.rb

Per https://github.com/flyerhzm/bullet/issues/637, API-only rails applications will fail to start when using bullet `7.0.5`.
https://github.com/flyerhzm/bullet/pull/634 made a change to insert the `Bullet::Rack` middleware before `ActionDispatch::ContentSecurityPolicy::Middleware`. This will only conditionally `insert_before` if `ActionDispatch::ContentSecurityPolicy::Middleware` is defined. It seems this is defined regardless of it being in the middleware stack or not.
This PR updates the logic to check if the `ActionDispatch::ContentSecurityPolicy::Middleware` middleware is in the stack, and if so, only then add `Bullet::Rack` before it.
You can validate this change using a API-only rails application. You can change an existing application to API only by adding `config.api_only = true` …

fix: don't insert bullet middleware before csp middleware in API only applications

---

CHANGELOG.md
lib/bullet/active_record4.rb
lib/bullet/active_record41.rb
lib/bullet/active_record42.rb
lib/bullet/active_record5.rb
lib/bullet/active_record52.rb
lib/bullet/active_record60.rb
lib/bullet/active_record61.rb
lib/bullet/active_record70.rb
lib/bullet/notification/counter_cache.rb
spec/bullet/notification/counter_cache_spec.rb
spec/integration/counter_cache_spec.rb

Just gauging interest here, as there may be a lot of considerations that I've missed. Generally people should use `size`, but if they use `count` the n+1 goes undetected. If you do want this in, we could backport it to older Rails versions.
Minimal example:
```ruby
class Blog < ApplicationRecord
has_many :comments, dependent: :destroy
end
MAX = 5
Blog.all.filter { |b| b.comments.count < MAX }
Blog.all.filter { |b| b.comments.size < MAX }
Blog.all.filter { |b| b.comments.length < MAX }
Blog.all.filter { |b| b.comments.to_a.count < MAX }
```

Detect n+1 count queries from ActiveRecord::Associations::CollectionProxy#count

---

lib/bullet.rb
spec/bullet_spec.rb

Perhaps a silly nitpick, but to me `Bullet.enabled?` reads a little bit more natural over currently provided `Bullet.enable?`, so I just made an alias in order to provide both APIs. Plus, added `Bullet.enabled=` alias for consistency.
Also, if it's acceptable, I'm happy to update the generator and documents to encourage the use of `enabled`.

Alias `Bullet.enable?` to `enabled?`, and `Bullet.enable=` to `enabled=`

---

Gemfile.mongoid-8.0
lib/bullet/dependency.rb
lib/bullet/mongoid8x.rb
spec/support/mongo_seed.rb
test.sh
update.sh

Mongoid 8.x support add

---

.github/workflows/main.yml
Gemfile.rails-7.1
lib/bullet/active_record71.rb
lib/bullet/dependency.rb
test.sh

I always use BULLET.
When rails7.1.0.beta1 was released and I was trying it out, I discovered that it is not supported by this Gem.
I would like to be able to use bullets in 7.1 as well.

Add Support ActiveRecord 7.1.0

---

lib/bullet/rack.rb
spec/bullet/rack_spec.rb

If using a "report only" CSP, bullet won't find/use the nonce thus will report bullet script tags as a policy violation. They will of course still execute, but with alerts for each script tag.
This change simply falls back to using the `Content-Security-Policy-Report-Only` header if the `Content-Security-Policy` header is not present, before falling back to an empty string.

Add support for `Content-Security-Policy-Report-Only` nonces

---

lib/bullet/ext/object.rb
spec/bullet/ext/object_spec.rb

ActiveRecord 7.1 added first-party support for composite primary keys, which changed the way the `primary_key` method behaves; specifically, in cases where a model or table has a composite primary key, this will return an array of attributes rather than just one.
Given this gem already has support for composite primary keys through the `composite_primary_keys` gem, I just extracted out the work done there to support Rails 7.1's approach.
Closes #685.

fix: Support ActiveRecord 7.1 composite primary keys

---

lib/bullet/mongoid8x.rb

* make `first` and `last` signatures compatible with mongoid 8 see https://www.mongodb.com/docs/mongoid/current/release-notes/mongoid-8.0/#-id_sort-option-on--first-last-removed
* `first` and `last` only take a limit value rather than an option set
fixes https://github.com/flyerhzm/bullet/issues/689

fix mongoid8

---

README.md
lib/bullet.rb
lib/bullet/notification/base.rb
spec/bullet/notification/base_spec.rb

While some may find the current OS user helpful, in other contexts, that user is randomly assigned and not material to the notification itself. Consider a deployment enviroment like Heroku, which will use a different OS user for each deployable, and each deploy.
It may also cause grouping issues in services like Sentry, which use the exception / notification content to determine whether the situation has occurred already.
This does not change the default behavior, but rather introduces a new option to skip including that information in notifications, for those who want to.

allow apps to not include the user in a notification

---

lib/bullet/active_record5.rb
lib/bullet/active_record60.rb

- This issue occurs when using (rails 6.0 or 5.0 or 5.1) and passing arguments to the `count` method
- `ArgumentError: wrong number of arguments (given 1, expected 0)`
- 95ffb25 did not fix active_record5.rb and active_record60.rb
- I have modified active_record5.rb  and active_record60.rb in the same way as 95ffb25
```ruby
require "bundler/inline"
gemfile(true) do
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem "rails", "~> 6.0.0"
gem "sqlite3"
gem "timeout"
gem "bullet", github: "flyerhzm/bullet", require: false
end
require "active_record"
require "minitest/autorun"
require "logger"
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveSupport::LogSubscriber.colorize_logging = false …
```

Fix count method signature for active_record5 and active_record60

---

.github/workflows/main.yml
Gemfile.rails-7.1
Gemfile.rails-7.2
lib/bullet/active_record72.rb
lib/bullet/dependency.rb
test.sh

Rails 7.2 is expected to be released soon, so I made this PR to support ActiveRecord 7.2.0.
https://rubygems.org/gems/rails/versions/7.2.0.beta1
Changes:
- Updated dependencies to work with ActiveRecord 7.2.0
- Made necessary code adjustments (The arguments of the `find_by_sql` method have changed.)

Support active record 7.2.0

---

spec/integration/active_record/association_spec.rb

There were some tests with data leaked out to other tests
```ruby
BUNDLE_GEMFILE=Gemfile.rails-7.2 bundle && BUNDLE_GEMFILE=Gemfile.rails-7.2 bundle exec rspec './spec/integration/active_record/association_spec.rb[1:5:1,2:1:6]' --seed 18477
Bundle complete! 7 Gemfile dependencies, 73 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Run options: include {:focus=>true, :ids=>{"./spec/integration/active_record/association_spec.rb"=>["1:5:1", "2:1:6"]}}
Randomized with seed 18477
.F
Failures:
1) Bullet::Detector::Association has_many category => posts => writer should not detect unused preload associations
Failure/Error: post.writer.name
NoMethodError:
undefined method `name' for nil
Finished in 0.15346 seconds (files took 0.48094 seconds to load)
2 …
```

Fix flaky spec

---

lib/bullet.rb
lib/bullet/detector/association.rb
lib/bullet/detector/counter_cache.rb
spec/integration/active_record/association_spec.rb

Bullet stores global objects into fiber-local variables before each request, uses these global objects to collect all N+1 queries and later shows all collected problems based on these global objects result. This approach works well until someone don't try to run his code inside Fiber like this
```ruby
class PostsController < ApplicationController
def index
fiber = ::Fiber.new do
Post.find_each do |post|
post.comments.each do |comment|
comment.name
end
end
end
fiber.resume
end
end
```
In that case bullet warning is not shown because all global objects are stored as fiber-local variables for current Fiber and not passed to all new Fibers
The easiest way is to store bullet objects into thread-local variables instead: https://ruby-doc.org/core-2.6/Thread.html#class-Thread-label-Fiber-local+vs. …

Store global objects into thread-local variables

---

lib/bullet/detector/association.rb
lib/bullet/detector/counter_cache.rb
lib/bullet/detector/n_plus_one_query.rb
lib/bullet/detector/unused_eager_loading.rb
lib/bullet/ext/object.rb
lib/bullet/ext/string.rb
lib/bullet/registry/object.rb
lib/bullet/stack_trace_filter.rb
spec/bullet/detector/association_spec.rb
spec/bullet/detector/counter_cache_spec.rb
spec/bullet/detector/n_plus_one_query_spec.rb
spec/bullet/detector/unused_eager_loading_spec.rb
spec/bullet/ext/object_spec.rb
spec/bullet/ext/string_spec.rb
spec/bullet/registry/object_spec.rb
spec/support/bullet_ext.rb

This gem monkey-patches Object class and String class with the following four methods for the gem internal use,
Object#bullet_key
Object#bullet_primary_key_value
Object#bullet_join_potential_composite_primary_key
String#bullet_class_name
and these methods are globally polluting every Object in the whole Ruby process.
This kind of monkey-patching is a dangerous approach and should be avoided in a gem that is usually bundled only in development/test, since it may become a cause of weird bugs that happen only on production env.
So, here's a patch that encapsulates these monkey-patches inside this gem by rewriting the core-exts to use refinements.
Note that this can be an incompatible change for those who use these methods from their application code. I can hardly imagine such a use case, but …

Make core extensions cleaner with refinements

---

lib/bullet/registry/call_stack.rb

With this simple trick, a local rails server with less than a dozen SQL  queries using AR drastically reduces the amount of memory allocated by  bullet.
before:
```
allocated memory by gem
-----------------------------------
796102  activesupport-7.2.1
726428  bullet/lib
```
after:
```
allocated memory by gem
-----------------------------------
794350  activesupport-7.2.1
313180  sprockets-4.2.1
259688  activerecord-7.2.1
204936  bullet/lib
```
Using the patched perf/benchmark.rb file to work with sqlite instead of  mysql, I saw reproductible numbers:
main
```
Querying & Iterating 1000 Posts with 10000 Comments and 100 Users                            
user     system      total        real
14.503545   0.638605  15.142150 ( 15.201747)
```
patch
```
Querying & Iterating 1000 Posts with …
```

Memoize call_stack registry for same key entry

---

README.md

Fix coderwall badge

---

.github/workflows/main.yml
lib/bullet/detector/association.rb
lib/bullet/detector/n_plus_one_query.rb
lib/bullet/ext/object.rb
lib/bullet/ext/string.rb
lib/bullet/stack_trace_filter.rb
perf/benchmark.rb
spec/bullet/detector/n_plus_one_query_spec.rb
spec/bullet/ext/object_spec.rb

As mentioned below, I'm unsure as to what is making the tests fail.
Benchmark:
Using a local projects page firing 42 queries and detecting one `include` missing:
On 8.0.0
```
allocated memory by gem
-----------------------------------
3598454  activesupport-8.0.0.1
1275662  bullet/lib
```
Patch:
```
allocated memory by gem
-----------------------------------
3598454  activesupport-8.0.0.1
1139414  bullet/lib
```
Running the benchmark:
8.0.0
```
1000 Posts with 10000 Comments and 100 Users       13.591269   0.893714  14.484983 ( 14.682978)
```
Patch:
```
1000 Posts with 10000 Comments and 100 Users        6.464706   0.390424   6.855130 (  7.152605)
```
Which is a surprising improvement, considering I was mostly aiming at reducing the memory usage. I suspect this will actually be more …

Reduce mem allocations

---

spec/bullet/ext/object_spec.rb

Post.first.reload wouldn't solve this as composite primary_key isn't  supported in older AR versions

Fix primary_key spec for older rails versions

---

lib/bullet.rb

When using bullet with Active Support on version 7.2 or greater, in a non-Rails project, an error is thrown during the initial load:
```
/Users/emil/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/delegation.rb:47:in `generate': uninitialized constant #<Class:ActiveSupport::Delegation>::Inflector (NameError)
unless Inflector.safe_constantize(to.name).equal?(to)
^^^^^^^^^
from /Users/emil/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/core_ext/module/delegation.rb:161:in `delegate'
from /Users/emil/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bullet-7.2.0/lib/bullet.rb:53:in `singleton class'
from /Users/emil/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bullet-7.2.0/lib/bullet.rb:35:in …
```

Require active_support's inflections module before requiring the delegation module

---

README.md

I was trying to integrate this gem in one of my Rails apps that uses Minitest for testing, and I noticed that in the README there are only guidelines on how to integrate it with `RSpec`.
With this PR I have added a section on how to integrate the gem on Minitest, which I'm pretty sure is used in a lot of Rails apps since it's the default testing library that Rails ships with :)
If this PR gets merged you can also close issue https://github.com/flyerhzm/bullet/issues/442 maybe :)

Add Minitest setup in README.md

---

README.md
lib/bullet.rb

fix https://github.com/flyerhzm/bullet/issues/703
This pull request includes changes to the `lib/bullet.rb` file to improve the handling of feature enablement flags by introducing default values and refactoring the enablement checks.
Refactoring of feature enablement flags:
* [`lib/bullet.rb`](diffhunk://#diff-56e8066b5abe8aa4937fd79797e591694ca827264b1fc8510da50b65ad89f495L67-R71): Modified the `enable=` method to set default values for `@n_plus_one_query_enable`, `@unused_eager_loading_enable`, and `@counter_cache_enable` if they are not already set.
* [`lib/bullet.rb`](diffhunk://#diff-56e8066b5abe8aa4937fd79797e591694ca827264b1fc8510da50b65ad89f495L93-R117): Refactored the `n_plus_one_query_enable?`, `unused_eager_loading_enable?`, and `counter_cache_enable?` methods to use new helper …

change Bullet's feature enable logic

---

CHANGELOG.md
README.md

Once uniform notifier is released, we can upgrade it here to add support for OpenTelemetry.

Document the uniform notifier support of otel

---

lib/bullet/rack.rb
spec/bullet/rack_spec.rb

Bullet does not currently render its footer with the expected styles when Rails `content_security_policy` configuration is the following.
```ruby
Rails.application.configure do
config.content_security_policy do |policy|
policy.script_src :self
policy.style_src :self
end
config.content_security_policy_nonce_directives = %w[script-src style-src]
end
```
This Pull Request replaces **style attributes** with **style tags** containing the expected `nonce` when required in the Rack middleware.

Add CSP nonce for footer styles as well

---

lib/bullet.rb

My app is adopting the Rails `Content-Security-Policy` header configuration and I began noticing that the injected javascript from Bullet started raising violations. From there, I checked out the source for the middleware and saw that CSP support exists.
The issue that became clear was the middleware was being added later in the middleware stack, despite the Railtie reading as if it's placing `Bullet::Rack` before `ActionDispatch::ContentSecurityPolicy::Middleware`.
Turned out that the initializers haven't run when this Railtie is ran, causing the `Rails.application.config.content_security_policy` to be `nil`.
Using `after: :load_config_initializers` avoids that issue and ensures the `content_security_policy` is present if one is defined.

Use middleware after initializers

---

README.md

There were inconsistencies between the code examples and descriptions in the Configuration section of the README.
**Issues**
- Different ordering of configuration items
- 4 items (`skip_http_headers`, `raise`, `always_append_html_body`, `skip_user_in_notification`) missing from code examples
- Unified the order of items between code examples and descriptions (with minimal changes)
- Added the 4 missing items to code examples
- Ensured all 22 items are completely aligned in both order and content
This makes the documentation more consistent and easier for developers to reference.

Tidy configuration section in README

---

lib/bullet/mongoid4x.rb
lib/bullet/mongoid5x.rb
lib/bullet/mongoid6x.rb
lib/bullet/mongoid7x.rb
lib/bullet/mongoid8x.rb
lib/bullet/mongoid9x.rb

This pull request restores the original visibility of Mongoid’s `get_relation` method to **private**.
Currently, requiring Bullet changes the visibility of `get_relation` from private to public because Bullet redefines it to patch its behavior.  
However, in Mongoid’s own implementation, `get_relation` has been private in **all versions from 4.x through 9.x**.
(see [v4.0.2](https://github.com/mongodb/mongoid/blob/v4.0.2/lib/mongoid/relations/accessors.rb#L78-L95), [v5.4.1](https://github.com/mongodb/mongoid/blob/v5.4.1/lib/mongoid/relations/accessors.rb#L77-L94), [v6.4.8](https://github.com/mongodb/mongoid/blob/v6.4.8/lib/mongoid/relations/accessors.rb#L77-L94), [v7.5.4](https://github.com/mongodb/mongoid/blob/v7.5.4/lib/mongoid/association/accessors.rb#L76-L92), …

Make `get_relation` private
